[tox]
env_list = py311, lint, format
isolated_build = true

[testenv]
extras = dev
commands = pytest

[testenv:lint]
extras = dev
commands = ruff check .

[testenv:format]
extras = dev
commands = ruff format --check .
